version: "3.7"

services:
  web:
    restart: always
    image: go-gin
    ports:
      - 8000:8080
    environment:
      MYSQL_USER: user_gallery
      MYSQL_PASSWORD: gallery-pwd
      MYSQL_DATABASE: jawadscript_dev
    links:
      -  db
    networks:
      - backend

  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user_gallery
      MYSQL_PASSWORD: gallery-pwd
      MYSQL_DATABASE: jawadscript_dev
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      DB_HOST: tcp(db:3306)
    volumes:
      - ./docker/data:/docker-entrypoint-initdb.d
    networks:
      - backend

networks:
  backend:
    driver: "bridge"