version: "3.7"

services:
  web:
    restart: always
    image: go-gin
    ports:
      - 8000:8000
    environment:
      MYSQL_USER: user_gallery
      MYSQL_PASSWORD: gallery-pwd
      MYSQL_DATABASE: jawadscript_dev
      DB_HOST: db:3306

    links:
      -  db
    networks:
      - backend

  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user_gallery
      MYSQL_PASSWORD: gallery-pwd
      MYSQL_DATABASE: jawadscript_dev
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db_data1:/var/lib/mysql
    networks:
      - backend

volumes:
  db_data1: {}

networks:
  backend:
    driver: "bridge"