version: '3.5'

services:
  web:
    restart: always
    image: go-gin
    ports:
      - 8080:8080
    links:
      -  db


  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: gallery
      MYSQL_PASSWORD: gallery
      MYSQL_DATABASE: image_gallery
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      DB_HOST: tcp(db:3306)
    volumes:
      - ./docker/data:/docker-entrypoint-initdb.d
    networks:
      - backend
